name: "MIND Lab"
description: "This is the official web page for the MIND Lab at UTA."

url: "https://lake233.github.io/zhulab.github.io/"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown: 
  parse_block_html: true

exclude: [vendor]
